### ISSUE TITLE
The cost function of MDN

### ISSUE THREAD

**Issue by nhatuan84** [taboola/mdn-tensorflow-notebook-example#1]
Hi,

I do not get the idea of the cost function.
y was generated by Normal distribution but it is fed to tf.distributions.Normal again?
Is it correct?

Regards,

**Comment by shakedzy** [comment]
Hi @nhatuan84 , `y` is originally generated by a Normal distribution - but in real life you do not know the original distribution. It can be anything. Normal distribution is just simple and easy, and therefore we used it in this demo as the noise to `y`.
We use the Normal distribution in the cost function because we want the model to try and fit the input to a Normal distribution. We do that because, again, in real-life we _don't know_ the real distribution of the data, and a Normal distribution is something we usually use when trying to generalize some unknown distribution.
So, to conclude - `y` is _generated_ using a Normal distribution for the sake of the demo, but is _modeled_ as a Normal distribution because this is what we'll try to do when we do not know the real data's distribution.
Hope this helped!
